# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: 'ko'
early_access: false

tone_instructions: |
  리뷰는 짧고 명확하게 작성해줘.
  문제 → 영향 → 대안 순서를 지켜줘.
  기본 기준은 React 18(18.2.0) + React Router v6 환경이야.

reviews:
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false

  path_filters:
    - '!node_modules/**'
    - '!dist/**'
    - '!build/**'
    - '!**/*.png'
    - '!**/*.jpg'
    - '!**/*.jpeg'
    - '!**/*.gif'
    - '!**/*.svg'
    - '!**/__generated__/**'
    - '!**/generated/**'
    - '!**/*.map'
    - '!**/*.min.*'
    - '!**/*.lock'

  path_instructions:
    - path: '**/*.{ts,tsx}'
      instructions: |
        React 18 기준의 렌더링 흐름과 hooks 사용이 적절한지 확인해줘.
        React Router v6 패턴에 맞는 구조인지 검토해줘.

        서버 상태는 TanStack Query 사용을 기본으로 가정하고,
        queryKey 안정성, enabled 조건, select 비용, invalidate/refetch 타이밍을 중점적으로 봐줘.

        전역 상태(Zustand/Redux Toolkit)는 UI 상태 중심으로 권장하고,
        서버 상태를 전역에 두는 경우에는 그 필요성을 근거와 함께 설명하도록 유도해줘.

        TailwindCSS v4 + shadcn UI 사용 시,
        className 중복/과도 사용이나 구조적인 문제가 있을 때만 언급해줘.
        접근성이나 스타일 취향 지적은 필수가 아니라 참고 사항으로만 다뤄줘.

        any 사용은 지양하고,
        불가피할 경우 사유와 범위를 명확히 하도록 코멘트해줘.

  auto_review:
    enabled: true
    drafts: false
    ignore_title_keywords:
      - 'WIP'
      - 'DO NOT MERGE'
      - 'DRAFT'
    base_branches:
      - 'main'
      - 'develop'
      - 'release/*'
      - 'feat/*'

chat:
  auto_reply: true
